parameters_description = {
    'sort_by': "Sort By (Available options are - carbon_sorting, latest, recycled_content, recyclable_content)",
    'group_by': "Products are grouped by (Available options are - company_name, product_type, material, manufacturing_location, continent, price_range, building_applications, building_types, certification_types)",
    'mf_unit': "Include dictionary with material facts in specified units. Accepts a single value or multiple values. Use 'all' to include all units. For example, to express material facts in square meters and square feet, use mf_unit='m2'&mf_unit='ft2'.",
    'name': "Search with the name of the product",
    'product_type': "Product Type Ids (e.g. product_type=2 or [2,3])",
    'product_type_family': "Product Type Family Ids (e.g. product_type_family=3 or [2,3])",
    'material_types': "Material Types Ids (e.g. material_types=4 or [2,3])",
    'material_types_family': "Material Types Family Ids (e.g. material_types_family=3 or [2,3])",
    'building_applications': "Building Applications Ids (e.g. building_applications=4 or [2,3])",
    'company': "Company Ids (e.g. company=4 or [22,23])",
    'building_types': "Building Types Ids (e.g. building_types=4 or [1,2,3,4])",
    'fire_performance': "Fire Performance Name (e.g. fire_performance= A1 or ['  B-s1,d0','M3 (NF P92-501 : 1995)'])",
    'manufacturing_country': "Manufacturing Country Ids (e.g. manufacturing_country=4 or manufacturing_country=United State)",
    'continent': "Continent Ids (e.g. continent=5 or [2,3])",
    'certificate_type': "Certificate Type Ids (e.g. certificate_type=2or [2,3])",
    'certificate_type_family': "Certificate Type Family Ids (e.g. certificate_type_family=1or [2,3])",
    'norm_price': "Norm Price Ids (e.g. norm_price=4 or [2,3])",
}

